// This file is generated by generate_rops_cases.py
case JointCs(CsArgb15, CsArgb15):
	if (Composite)
		GComposite15To15((GArgb15*)d, (GArgb15*)s, x);
	else
		GRop15To15((GArgb15*)d, (GArgb15*)s, x);
	break;
case JointCs(CsArgb15, CsRgb15):
	GRop15To15((GArgb15*)d, (GRgb15*)s, x);
	break;
case JointCs(CsArgb15, CsAbgr15):
	if (Composite)
		GComposite15To15((GArgb15*)d, (GAbgr15*)s, x);
	else
		GRop15To15((GArgb15*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsArgb15, CsBgr15):
	GRop15To15((GArgb15*)d, (GBgr15*)s, x);
	break;
case JointCs(CsArgb15, CsRgb16):
	GRop16To15((GArgb15*)d, (GRgb16*)s, x);
	break;
case JointCs(CsArgb15, CsBgr16):
	GRop16To15((GArgb15*)d, (GBgr16*)s, x);
	break;
case JointCs(CsArgb15, CsRgb24):
	GRop24To15((GArgb15*)d, (GRgb24*)s, x);
	break;
case JointCs(CsArgb15, CsBgr24):
	GRop24To15((GArgb15*)d, (GBgr24*)s, x);
	break;
case JointCs(CsArgb15, CsRgbx32):
	GRop24To15((GArgb15*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsArgb15, CsBgrx32):
	GRop24To15((GArgb15*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsArgb15, CsXrgb32):
	GRop24To15((GArgb15*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsArgb15, CsXbgr32):
	GRop24To15((GArgb15*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsArgb15, CsRgba32):
	if (Composite)
		GComposite32To15((GArgb15*)d, (GRgba32*)s, x);
	else
		GRop32To15((GArgb15*)d, (GRgba32*)s, x);
	break;
case JointCs(CsArgb15, CsBgra32):
	if (Composite)
		GComposite32To15((GArgb15*)d, (GBgra32*)s, x);
	else
		GRop32To15((GArgb15*)d, (GBgra32*)s, x);
	break;
case JointCs(CsArgb15, CsArgb32):
	if (Composite)
		GComposite32To15((GArgb15*)d, (GArgb32*)s, x);
	else
		GRop32To15((GArgb15*)d, (GArgb32*)s, x);
	break;
case JointCs(CsArgb15, CsAbgr32):
	if (Composite)
		GComposite32To15((GArgb15*)d, (GAbgr32*)s, x);
	else
		GRop32To15((GArgb15*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsArgb15, CsBgr48):
	GRop48To15((GArgb15*)d, (GBgr48*)s, x);
	break;
case JointCs(CsArgb15, CsRgb48):
	GRop48To15((GArgb15*)d, (GRgb48*)s, x);
	break;
case JointCs(CsArgb15, CsBgra64):
	if (Composite)
		GComposite64To15((GArgb15*)d, (GBgra64*)s, x);
	else
		GRop64To15((GArgb15*)d, (GBgra64*)s, x);
	break;
case JointCs(CsArgb15, CsRgba64):
	if (Composite)
		GComposite64To15((GArgb15*)d, (GRgba64*)s, x);
	else
		GRop64To15((GArgb15*)d, (GRgba64*)s, x);
	break;
case JointCs(CsArgb15, CsAbgr64):
	if (Composite)
		GComposite64To15((GArgb15*)d, (GAbgr64*)s, x);
	else
		GRop64To15((GArgb15*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsArgb15, CsArgb64):
	if (Composite)
		GComposite64To15((GArgb15*)d, (GArgb64*)s, x);
	else
		GRop64To15((GArgb15*)d, (GArgb64*)s, x);
	break;
case JointCs(CsRgb15, CsArgb15):
	if (Composite)
		GComposite15To15((GRgb15*)d, (GArgb15*)s, x);
	else
		GRop15To15((GRgb15*)d, (GArgb15*)s, x);
	break;
case JointCs(CsRgb15, CsRgb15):
	GRop15To15((GRgb15*)d, (GRgb15*)s, x);
	break;
case JointCs(CsRgb15, CsAbgr15):
	if (Composite)
		GComposite15To15((GRgb15*)d, (GAbgr15*)s, x);
	else
		GRop15To15((GRgb15*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsRgb15, CsBgr15):
	GRop15To15((GRgb15*)d, (GBgr15*)s, x);
	break;
case JointCs(CsRgb15, CsRgb16):
	GRop16To15((GRgb15*)d, (GRgb16*)s, x);
	break;
case JointCs(CsRgb15, CsBgr16):
	GRop16To15((GRgb15*)d, (GBgr16*)s, x);
	break;
case JointCs(CsRgb15, CsRgb24):
	GRop24To15((GRgb15*)d, (GRgb24*)s, x);
	break;
case JointCs(CsRgb15, CsBgr24):
	GRop24To15((GRgb15*)d, (GBgr24*)s, x);
	break;
case JointCs(CsRgb15, CsRgbx32):
	GRop24To15((GRgb15*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsRgb15, CsBgrx32):
	GRop24To15((GRgb15*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsRgb15, CsXrgb32):
	GRop24To15((GRgb15*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsRgb15, CsXbgr32):
	GRop24To15((GRgb15*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsRgb15, CsRgba32):
	if (Composite)
		GComposite32To15((GRgb15*)d, (GRgba32*)s, x);
	else
		GRop32To15((GRgb15*)d, (GRgba32*)s, x);
	break;
case JointCs(CsRgb15, CsBgra32):
	if (Composite)
		GComposite32To15((GRgb15*)d, (GBgra32*)s, x);
	else
		GRop32To15((GRgb15*)d, (GBgra32*)s, x);
	break;
case JointCs(CsRgb15, CsArgb32):
	if (Composite)
		GComposite32To15((GRgb15*)d, (GArgb32*)s, x);
	else
		GRop32To15((GRgb15*)d, (GArgb32*)s, x);
	break;
case JointCs(CsRgb15, CsAbgr32):
	if (Composite)
		GComposite32To15((GRgb15*)d, (GAbgr32*)s, x);
	else
		GRop32To15((GRgb15*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsRgb15, CsBgr48):
	GRop48To15((GRgb15*)d, (GBgr48*)s, x);
	break;
case JointCs(CsRgb15, CsRgb48):
	GRop48To15((GRgb15*)d, (GRgb48*)s, x);
	break;
case JointCs(CsRgb15, CsBgra64):
	if (Composite)
		GComposite64To15((GRgb15*)d, (GBgra64*)s, x);
	else
		GRop64To15((GRgb15*)d, (GBgra64*)s, x);
	break;
case JointCs(CsRgb15, CsRgba64):
	if (Composite)
		GComposite64To15((GRgb15*)d, (GRgba64*)s, x);
	else
		GRop64To15((GRgb15*)d, (GRgba64*)s, x);
	break;
case JointCs(CsRgb15, CsAbgr64):
	if (Composite)
		GComposite64To15((GRgb15*)d, (GAbgr64*)s, x);
	else
		GRop64To15((GRgb15*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsRgb15, CsArgb64):
	if (Composite)
		GComposite64To15((GRgb15*)d, (GArgb64*)s, x);
	else
		GRop64To15((GRgb15*)d, (GArgb64*)s, x);
	break;
case JointCs(CsAbgr15, CsArgb15):
	if (Composite)
		GComposite15To15((GAbgr15*)d, (GArgb15*)s, x);
	else
		GRop15To15((GAbgr15*)d, (GArgb15*)s, x);
	break;
case JointCs(CsAbgr15, CsRgb15):
	GRop15To15((GAbgr15*)d, (GRgb15*)s, x);
	break;
case JointCs(CsAbgr15, CsAbgr15):
	if (Composite)
		GComposite15To15((GAbgr15*)d, (GAbgr15*)s, x);
	else
		GRop15To15((GAbgr15*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsAbgr15, CsBgr15):
	GRop15To15((GAbgr15*)d, (GBgr15*)s, x);
	break;
case JointCs(CsAbgr15, CsRgb16):
	GRop16To15((GAbgr15*)d, (GRgb16*)s, x);
	break;
case JointCs(CsAbgr15, CsBgr16):
	GRop16To15((GAbgr15*)d, (GBgr16*)s, x);
	break;
case JointCs(CsAbgr15, CsRgb24):
	GRop24To15((GAbgr15*)d, (GRgb24*)s, x);
	break;
case JointCs(CsAbgr15, CsBgr24):
	GRop24To15((GAbgr15*)d, (GBgr24*)s, x);
	break;
case JointCs(CsAbgr15, CsRgbx32):
	GRop24To15((GAbgr15*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsAbgr15, CsBgrx32):
	GRop24To15((GAbgr15*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsAbgr15, CsXrgb32):
	GRop24To15((GAbgr15*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsAbgr15, CsXbgr32):
	GRop24To15((GAbgr15*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsAbgr15, CsRgba32):
	if (Composite)
		GComposite32To15((GAbgr15*)d, (GRgba32*)s, x);
	else
		GRop32To15((GAbgr15*)d, (GRgba32*)s, x);
	break;
case JointCs(CsAbgr15, CsBgra32):
	if (Composite)
		GComposite32To15((GAbgr15*)d, (GBgra32*)s, x);
	else
		GRop32To15((GAbgr15*)d, (GBgra32*)s, x);
	break;
case JointCs(CsAbgr15, CsArgb32):
	if (Composite)
		GComposite32To15((GAbgr15*)d, (GArgb32*)s, x);
	else
		GRop32To15((GAbgr15*)d, (GArgb32*)s, x);
	break;
case JointCs(CsAbgr15, CsAbgr32):
	if (Composite)
		GComposite32To15((GAbgr15*)d, (GAbgr32*)s, x);
	else
		GRop32To15((GAbgr15*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsAbgr15, CsBgr48):
	GRop48To15((GAbgr15*)d, (GBgr48*)s, x);
	break;
case JointCs(CsAbgr15, CsRgb48):
	GRop48To15((GAbgr15*)d, (GRgb48*)s, x);
	break;
case JointCs(CsAbgr15, CsBgra64):
	if (Composite)
		GComposite64To15((GAbgr15*)d, (GBgra64*)s, x);
	else
		GRop64To15((GAbgr15*)d, (GBgra64*)s, x);
	break;
case JointCs(CsAbgr15, CsRgba64):
	if (Composite)
		GComposite64To15((GAbgr15*)d, (GRgba64*)s, x);
	else
		GRop64To15((GAbgr15*)d, (GRgba64*)s, x);
	break;
case JointCs(CsAbgr15, CsAbgr64):
	if (Composite)
		GComposite64To15((GAbgr15*)d, (GAbgr64*)s, x);
	else
		GRop64To15((GAbgr15*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsAbgr15, CsArgb64):
	if (Composite)
		GComposite64To15((GAbgr15*)d, (GArgb64*)s, x);
	else
		GRop64To15((GAbgr15*)d, (GArgb64*)s, x);
	break;
case JointCs(CsBgr15, CsArgb15):
	if (Composite)
		GComposite15To15((GBgr15*)d, (GArgb15*)s, x);
	else
		GRop15To15((GBgr15*)d, (GArgb15*)s, x);
	break;
case JointCs(CsBgr15, CsRgb15):
	GRop15To15((GBgr15*)d, (GRgb15*)s, x);
	break;
case JointCs(CsBgr15, CsAbgr15):
	if (Composite)
		GComposite15To15((GBgr15*)d, (GAbgr15*)s, x);
	else
		GRop15To15((GBgr15*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsBgr15, CsBgr15):
	GRop15To15((GBgr15*)d, (GBgr15*)s, x);
	break;
case JointCs(CsBgr15, CsRgb16):
	GRop16To15((GBgr15*)d, (GRgb16*)s, x);
	break;
case JointCs(CsBgr15, CsBgr16):
	GRop16To15((GBgr15*)d, (GBgr16*)s, x);
	break;
case JointCs(CsBgr15, CsRgb24):
	GRop24To15((GBgr15*)d, (GRgb24*)s, x);
	break;
case JointCs(CsBgr15, CsBgr24):
	GRop24To15((GBgr15*)d, (GBgr24*)s, x);
	break;
case JointCs(CsBgr15, CsRgbx32):
	GRop24To15((GBgr15*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsBgr15, CsBgrx32):
	GRop24To15((GBgr15*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsBgr15, CsXrgb32):
	GRop24To15((GBgr15*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsBgr15, CsXbgr32):
	GRop24To15((GBgr15*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsBgr15, CsRgba32):
	if (Composite)
		GComposite32To15((GBgr15*)d, (GRgba32*)s, x);
	else
		GRop32To15((GBgr15*)d, (GRgba32*)s, x);
	break;
case JointCs(CsBgr15, CsBgra32):
	if (Composite)
		GComposite32To15((GBgr15*)d, (GBgra32*)s, x);
	else
		GRop32To15((GBgr15*)d, (GBgra32*)s, x);
	break;
case JointCs(CsBgr15, CsArgb32):
	if (Composite)
		GComposite32To15((GBgr15*)d, (GArgb32*)s, x);
	else
		GRop32To15((GBgr15*)d, (GArgb32*)s, x);
	break;
case JointCs(CsBgr15, CsAbgr32):
	if (Composite)
		GComposite32To15((GBgr15*)d, (GAbgr32*)s, x);
	else
		GRop32To15((GBgr15*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsBgr15, CsBgr48):
	GRop48To15((GBgr15*)d, (GBgr48*)s, x);
	break;
case JointCs(CsBgr15, CsRgb48):
	GRop48To15((GBgr15*)d, (GRgb48*)s, x);
	break;
case JointCs(CsBgr15, CsBgra64):
	if (Composite)
		GComposite64To15((GBgr15*)d, (GBgra64*)s, x);
	else
		GRop64To15((GBgr15*)d, (GBgra64*)s, x);
	break;
case JointCs(CsBgr15, CsRgba64):
	if (Composite)
		GComposite64To15((GBgr15*)d, (GRgba64*)s, x);
	else
		GRop64To15((GBgr15*)d, (GRgba64*)s, x);
	break;
case JointCs(CsBgr15, CsAbgr64):
	if (Composite)
		GComposite64To15((GBgr15*)d, (GAbgr64*)s, x);
	else
		GRop64To15((GBgr15*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsBgr15, CsArgb64):
	if (Composite)
		GComposite64To15((GBgr15*)d, (GArgb64*)s, x);
	else
		GRop64To15((GBgr15*)d, (GArgb64*)s, x);
	break;
case JointCs(CsRgb16, CsArgb15):
	if (Composite)
		GComposite15To16((GRgb16*)d, (GArgb15*)s, x);
	else
		GRop15To16((GRgb16*)d, (GArgb15*)s, x);
	break;
case JointCs(CsRgb16, CsRgb15):
	GRop15To16((GRgb16*)d, (GRgb15*)s, x);
	break;
case JointCs(CsRgb16, CsAbgr15):
	if (Composite)
		GComposite15To16((GRgb16*)d, (GAbgr15*)s, x);
	else
		GRop15To16((GRgb16*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsRgb16, CsBgr15):
	GRop15To16((GRgb16*)d, (GBgr15*)s, x);
	break;
case JointCs(CsRgb16, CsRgb16):
	GRop16To16((GRgb16*)d, (GRgb16*)s, x);
	break;
case JointCs(CsRgb16, CsBgr16):
	GRop16To16((GRgb16*)d, (GBgr16*)s, x);
	break;
case JointCs(CsRgb16, CsRgb24):
	GRop24To16((GRgb16*)d, (GRgb24*)s, x);
	break;
case JointCs(CsRgb16, CsBgr24):
	GRop24To16((GRgb16*)d, (GBgr24*)s, x);
	break;
case JointCs(CsRgb16, CsRgbx32):
	GRop24To16((GRgb16*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsRgb16, CsBgrx32):
	GRop24To16((GRgb16*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsRgb16, CsXrgb32):
	GRop24To16((GRgb16*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsRgb16, CsXbgr32):
	GRop24To16((GRgb16*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsRgb16, CsRgba32):
	if (Composite)
		GComposite32To16((GRgb16*)d, (GRgba32*)s, x);
	else
		GRop32To16((GRgb16*)d, (GRgba32*)s, x);
	break;
case JointCs(CsRgb16, CsBgra32):
	if (Composite)
		GComposite32To16((GRgb16*)d, (GBgra32*)s, x);
	else
		GRop32To16((GRgb16*)d, (GBgra32*)s, x);
	break;
case JointCs(CsRgb16, CsArgb32):
	if (Composite)
		GComposite32To16((GRgb16*)d, (GArgb32*)s, x);
	else
		GRop32To16((GRgb16*)d, (GArgb32*)s, x);
	break;
case JointCs(CsRgb16, CsAbgr32):
	if (Composite)
		GComposite32To16((GRgb16*)d, (GAbgr32*)s, x);
	else
		GRop32To16((GRgb16*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsRgb16, CsBgr48):
	GRop48To16((GRgb16*)d, (GBgr48*)s, x);
	break;
case JointCs(CsRgb16, CsRgb48):
	GRop48To16((GRgb16*)d, (GRgb48*)s, x);
	break;
case JointCs(CsRgb16, CsBgra64):
	if (Composite)
		GComposite64To16((GRgb16*)d, (GBgra64*)s, x);
	else
		GRop64To16((GRgb16*)d, (GBgra64*)s, x);
	break;
case JointCs(CsRgb16, CsRgba64):
	if (Composite)
		GComposite64To16((GRgb16*)d, (GRgba64*)s, x);
	else
		GRop64To16((GRgb16*)d, (GRgba64*)s, x);
	break;
case JointCs(CsRgb16, CsAbgr64):
	if (Composite)
		GComposite64To16((GRgb16*)d, (GAbgr64*)s, x);
	else
		GRop64To16((GRgb16*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsRgb16, CsArgb64):
	if (Composite)
		GComposite64To16((GRgb16*)d, (GArgb64*)s, x);
	else
		GRop64To16((GRgb16*)d, (GArgb64*)s, x);
	break;
case JointCs(CsBgr16, CsArgb15):
	if (Composite)
		GComposite15To16((GBgr16*)d, (GArgb15*)s, x);
	else
		GRop15To16((GBgr16*)d, (GArgb15*)s, x);
	break;
case JointCs(CsBgr16, CsRgb15):
	GRop15To16((GBgr16*)d, (GRgb15*)s, x);
	break;
case JointCs(CsBgr16, CsAbgr15):
	if (Composite)
		GComposite15To16((GBgr16*)d, (GAbgr15*)s, x);
	else
		GRop15To16((GBgr16*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsBgr16, CsBgr15):
	GRop15To16((GBgr16*)d, (GBgr15*)s, x);
	break;
case JointCs(CsBgr16, CsRgb16):
	GRop16To16((GBgr16*)d, (GRgb16*)s, x);
	break;
case JointCs(CsBgr16, CsBgr16):
	GRop16To16((GBgr16*)d, (GBgr16*)s, x);
	break;
case JointCs(CsBgr16, CsRgb24):
	GRop24To16((GBgr16*)d, (GRgb24*)s, x);
	break;
case JointCs(CsBgr16, CsBgr24):
	GRop24To16((GBgr16*)d, (GBgr24*)s, x);
	break;
case JointCs(CsBgr16, CsRgbx32):
	GRop24To16((GBgr16*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsBgr16, CsBgrx32):
	GRop24To16((GBgr16*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsBgr16, CsXrgb32):
	GRop24To16((GBgr16*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsBgr16, CsXbgr32):
	GRop24To16((GBgr16*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsBgr16, CsRgba32):
	if (Composite)
		GComposite32To16((GBgr16*)d, (GRgba32*)s, x);
	else
		GRop32To16((GBgr16*)d, (GRgba32*)s, x);
	break;
case JointCs(CsBgr16, CsBgra32):
	if (Composite)
		GComposite32To16((GBgr16*)d, (GBgra32*)s, x);
	else
		GRop32To16((GBgr16*)d, (GBgra32*)s, x);
	break;
case JointCs(CsBgr16, CsArgb32):
	if (Composite)
		GComposite32To16((GBgr16*)d, (GArgb32*)s, x);
	else
		GRop32To16((GBgr16*)d, (GArgb32*)s, x);
	break;
case JointCs(CsBgr16, CsAbgr32):
	if (Composite)
		GComposite32To16((GBgr16*)d, (GAbgr32*)s, x);
	else
		GRop32To16((GBgr16*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsBgr16, CsBgr48):
	GRop48To16((GBgr16*)d, (GBgr48*)s, x);
	break;
case JointCs(CsBgr16, CsRgb48):
	GRop48To16((GBgr16*)d, (GRgb48*)s, x);
	break;
case JointCs(CsBgr16, CsBgra64):
	if (Composite)
		GComposite64To16((GBgr16*)d, (GBgra64*)s, x);
	else
		GRop64To16((GBgr16*)d, (GBgra64*)s, x);
	break;
case JointCs(CsBgr16, CsRgba64):
	if (Composite)
		GComposite64To16((GBgr16*)d, (GRgba64*)s, x);
	else
		GRop64To16((GBgr16*)d, (GRgba64*)s, x);
	break;
case JointCs(CsBgr16, CsAbgr64):
	if (Composite)
		GComposite64To16((GBgr16*)d, (GAbgr64*)s, x);
	else
		GRop64To16((GBgr16*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsBgr16, CsArgb64):
	if (Composite)
		GComposite64To16((GBgr16*)d, (GArgb64*)s, x);
	else
		GRop64To16((GBgr16*)d, (GArgb64*)s, x);
	break;
case JointCs(CsRgb24, CsArgb15):
	if (Composite)
		GComposite15To24((GRgb24*)d, (GArgb15*)s, x);
	else
		GRop15To24((GRgb24*)d, (GArgb15*)s, x);
	break;
case JointCs(CsRgb24, CsRgb15):
	GRop15To24((GRgb24*)d, (GRgb15*)s, x);
	break;
case JointCs(CsRgb24, CsAbgr15):
	if (Composite)
		GComposite15To24((GRgb24*)d, (GAbgr15*)s, x);
	else
		GRop15To24((GRgb24*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsRgb24, CsBgr15):
	GRop15To24((GRgb24*)d, (GBgr15*)s, x);
	break;
case JointCs(CsRgb24, CsRgb16):
	GRop16To24((GRgb24*)d, (GRgb16*)s, x);
	break;
case JointCs(CsRgb24, CsBgr16):
	GRop16To24((GRgb24*)d, (GBgr16*)s, x);
	break;
case JointCs(CsRgb24, CsRgb24):
	GRop24To24((GRgb24*)d, (GRgb24*)s, x);
	break;
case JointCs(CsRgb24, CsBgr24):
	GRop24To24((GRgb24*)d, (GBgr24*)s, x);
	break;
case JointCs(CsRgb24, CsRgbx32):
	GRop24To24((GRgb24*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsRgb24, CsBgrx32):
	GRop24To24((GRgb24*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsRgb24, CsXrgb32):
	GRop24To24((GRgb24*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsRgb24, CsXbgr32):
	GRop24To24((GRgb24*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsRgb24, CsRgba32):
	if (Composite)
		GComposite32To24((GRgb24*)d, (GRgba32*)s, x);
	else
		GRop32To24((GRgb24*)d, (GRgba32*)s, x);
	break;
case JointCs(CsRgb24, CsBgra32):
	if (Composite)
		GComposite32To24((GRgb24*)d, (GBgra32*)s, x);
	else
		GRop32To24((GRgb24*)d, (GBgra32*)s, x);
	break;
case JointCs(CsRgb24, CsArgb32):
	if (Composite)
		GComposite32To24((GRgb24*)d, (GArgb32*)s, x);
	else
		GRop32To24((GRgb24*)d, (GArgb32*)s, x);
	break;
case JointCs(CsRgb24, CsAbgr32):
	if (Composite)
		GComposite32To24((GRgb24*)d, (GAbgr32*)s, x);
	else
		GRop32To24((GRgb24*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsRgb24, CsBgr48):
	GRop48To24((GRgb24*)d, (GBgr48*)s, x);
	break;
case JointCs(CsRgb24, CsRgb48):
	GRop48To24((GRgb24*)d, (GRgb48*)s, x);
	break;
case JointCs(CsRgb24, CsBgra64):
	if (Composite)
		GComposite64To24((GRgb24*)d, (GBgra64*)s, x);
	else
		GRop64To24((GRgb24*)d, (GBgra64*)s, x);
	break;
case JointCs(CsRgb24, CsRgba64):
	if (Composite)
		GComposite64To24((GRgb24*)d, (GRgba64*)s, x);
	else
		GRop64To24((GRgb24*)d, (GRgba64*)s, x);
	break;
case JointCs(CsRgb24, CsAbgr64):
	if (Composite)
		GComposite64To24((GRgb24*)d, (GAbgr64*)s, x);
	else
		GRop64To24((GRgb24*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsRgb24, CsArgb64):
	if (Composite)
		GComposite64To24((GRgb24*)d, (GArgb64*)s, x);
	else
		GRop64To24((GRgb24*)d, (GArgb64*)s, x);
	break;
case JointCs(CsBgr24, CsArgb15):
	if (Composite)
		GComposite15To24((GBgr24*)d, (GArgb15*)s, x);
	else
		GRop15To24((GBgr24*)d, (GArgb15*)s, x);
	break;
case JointCs(CsBgr24, CsRgb15):
	GRop15To24((GBgr24*)d, (GRgb15*)s, x);
	break;
case JointCs(CsBgr24, CsAbgr15):
	if (Composite)
		GComposite15To24((GBgr24*)d, (GAbgr15*)s, x);
	else
		GRop15To24((GBgr24*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsBgr24, CsBgr15):
	GRop15To24((GBgr24*)d, (GBgr15*)s, x);
	break;
case JointCs(CsBgr24, CsRgb16):
	GRop16To24((GBgr24*)d, (GRgb16*)s, x);
	break;
case JointCs(CsBgr24, CsBgr16):
	GRop16To24((GBgr24*)d, (GBgr16*)s, x);
	break;
case JointCs(CsBgr24, CsRgb24):
	GRop24To24((GBgr24*)d, (GRgb24*)s, x);
	break;
case JointCs(CsBgr24, CsBgr24):
	GRop24To24((GBgr24*)d, (GBgr24*)s, x);
	break;
case JointCs(CsBgr24, CsRgbx32):
	GRop24To24((GBgr24*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsBgr24, CsBgrx32):
	GRop24To24((GBgr24*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsBgr24, CsXrgb32):
	GRop24To24((GBgr24*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsBgr24, CsXbgr32):
	GRop24To24((GBgr24*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsBgr24, CsRgba32):
	if (Composite)
		GComposite32To24((GBgr24*)d, (GRgba32*)s, x);
	else
		GRop32To24((GBgr24*)d, (GRgba32*)s, x);
	break;
case JointCs(CsBgr24, CsBgra32):
	if (Composite)
		GComposite32To24((GBgr24*)d, (GBgra32*)s, x);
	else
		GRop32To24((GBgr24*)d, (GBgra32*)s, x);
	break;
case JointCs(CsBgr24, CsArgb32):
	if (Composite)
		GComposite32To24((GBgr24*)d, (GArgb32*)s, x);
	else
		GRop32To24((GBgr24*)d, (GArgb32*)s, x);
	break;
case JointCs(CsBgr24, CsAbgr32):
	if (Composite)
		GComposite32To24((GBgr24*)d, (GAbgr32*)s, x);
	else
		GRop32To24((GBgr24*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsBgr24, CsBgr48):
	GRop48To24((GBgr24*)d, (GBgr48*)s, x);
	break;
case JointCs(CsBgr24, CsRgb48):
	GRop48To24((GBgr24*)d, (GRgb48*)s, x);
	break;
case JointCs(CsBgr24, CsBgra64):
	if (Composite)
		GComposite64To24((GBgr24*)d, (GBgra64*)s, x);
	else
		GRop64To24((GBgr24*)d, (GBgra64*)s, x);
	break;
case JointCs(CsBgr24, CsRgba64):
	if (Composite)
		GComposite64To24((GBgr24*)d, (GRgba64*)s, x);
	else
		GRop64To24((GBgr24*)d, (GRgba64*)s, x);
	break;
case JointCs(CsBgr24, CsAbgr64):
	if (Composite)
		GComposite64To24((GBgr24*)d, (GAbgr64*)s, x);
	else
		GRop64To24((GBgr24*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsBgr24, CsArgb64):
	if (Composite)
		GComposite64To24((GBgr24*)d, (GArgb64*)s, x);
	else
		GRop64To24((GBgr24*)d, (GArgb64*)s, x);
	break;
case JointCs(CsRgbx32, CsArgb15):
	if (Composite)
		GComposite15To24((GRgbx32*)d, (GArgb15*)s, x);
	else
		GRop15To24((GRgbx32*)d, (GArgb15*)s, x);
	break;
case JointCs(CsRgbx32, CsRgb15):
	GRop15To24((GRgbx32*)d, (GRgb15*)s, x);
	break;
case JointCs(CsRgbx32, CsAbgr15):
	if (Composite)
		GComposite15To24((GRgbx32*)d, (GAbgr15*)s, x);
	else
		GRop15To24((GRgbx32*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsRgbx32, CsBgr15):
	GRop15To24((GRgbx32*)d, (GBgr15*)s, x);
	break;
case JointCs(CsRgbx32, CsRgb16):
	GRop16To24((GRgbx32*)d, (GRgb16*)s, x);
	break;
case JointCs(CsRgbx32, CsBgr16):
	GRop16To24((GRgbx32*)d, (GBgr16*)s, x);
	break;
case JointCs(CsRgbx32, CsRgb24):
	GRop24To24((GRgbx32*)d, (GRgb24*)s, x);
	break;
case JointCs(CsRgbx32, CsBgr24):
	GRop24To24((GRgbx32*)d, (GBgr24*)s, x);
	break;
case JointCs(CsRgbx32, CsRgbx32):
	GRop24To24((GRgbx32*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsRgbx32, CsBgrx32):
	GRop24To24((GRgbx32*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsRgbx32, CsXrgb32):
	GRop24To24((GRgbx32*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsRgbx32, CsXbgr32):
	GRop24To24((GRgbx32*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsRgbx32, CsRgba32):
	if (Composite)
		GComposite32To24((GRgbx32*)d, (GRgba32*)s, x);
	else
		GRop32To24((GRgbx32*)d, (GRgba32*)s, x);
	break;
case JointCs(CsRgbx32, CsBgra32):
	if (Composite)
		GComposite32To24((GRgbx32*)d, (GBgra32*)s, x);
	else
		GRop32To24((GRgbx32*)d, (GBgra32*)s, x);
	break;
case JointCs(CsRgbx32, CsArgb32):
	if (Composite)
		GComposite32To24((GRgbx32*)d, (GArgb32*)s, x);
	else
		GRop32To24((GRgbx32*)d, (GArgb32*)s, x);
	break;
case JointCs(CsRgbx32, CsAbgr32):
	if (Composite)
		GComposite32To24((GRgbx32*)d, (GAbgr32*)s, x);
	else
		GRop32To24((GRgbx32*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsRgbx32, CsBgr48):
	GRop48To24((GRgbx32*)d, (GBgr48*)s, x);
	break;
case JointCs(CsRgbx32, CsRgb48):
	GRop48To24((GRgbx32*)d, (GRgb48*)s, x);
	break;
case JointCs(CsRgbx32, CsBgra64):
	if (Composite)
		GComposite64To24((GRgbx32*)d, (GBgra64*)s, x);
	else
		GRop64To24((GRgbx32*)d, (GBgra64*)s, x);
	break;
case JointCs(CsRgbx32, CsRgba64):
	if (Composite)
		GComposite64To24((GRgbx32*)d, (GRgba64*)s, x);
	else
		GRop64To24((GRgbx32*)d, (GRgba64*)s, x);
	break;
case JointCs(CsRgbx32, CsAbgr64):
	if (Composite)
		GComposite64To24((GRgbx32*)d, (GAbgr64*)s, x);
	else
		GRop64To24((GRgbx32*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsRgbx32, CsArgb64):
	if (Composite)
		GComposite64To24((GRgbx32*)d, (GArgb64*)s, x);
	else
		GRop64To24((GRgbx32*)d, (GArgb64*)s, x);
	break;
case JointCs(CsBgrx32, CsArgb15):
	if (Composite)
		GComposite15To24((GBgrx32*)d, (GArgb15*)s, x);
	else
		GRop15To24((GBgrx32*)d, (GArgb15*)s, x);
	break;
case JointCs(CsBgrx32, CsRgb15):
	GRop15To24((GBgrx32*)d, (GRgb15*)s, x);
	break;
case JointCs(CsBgrx32, CsAbgr15):
	if (Composite)
		GComposite15To24((GBgrx32*)d, (GAbgr15*)s, x);
	else
		GRop15To24((GBgrx32*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsBgrx32, CsBgr15):
	GRop15To24((GBgrx32*)d, (GBgr15*)s, x);
	break;
case JointCs(CsBgrx32, CsRgb16):
	GRop16To24((GBgrx32*)d, (GRgb16*)s, x);
	break;
case JointCs(CsBgrx32, CsBgr16):
	GRop16To24((GBgrx32*)d, (GBgr16*)s, x);
	break;
case JointCs(CsBgrx32, CsRgb24):
	GRop24To24((GBgrx32*)d, (GRgb24*)s, x);
	break;
case JointCs(CsBgrx32, CsBgr24):
	GRop24To24((GBgrx32*)d, (GBgr24*)s, x);
	break;
case JointCs(CsBgrx32, CsRgbx32):
	GRop24To24((GBgrx32*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsBgrx32, CsBgrx32):
	GRop24To24((GBgrx32*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsBgrx32, CsXrgb32):
	GRop24To24((GBgrx32*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsBgrx32, CsXbgr32):
	GRop24To24((GBgrx32*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsBgrx32, CsRgba32):
	if (Composite)
		GComposite32To24((GBgrx32*)d, (GRgba32*)s, x);
	else
		GRop32To24((GBgrx32*)d, (GRgba32*)s, x);
	break;
case JointCs(CsBgrx32, CsBgra32):
	if (Composite)
		GComposite32To24((GBgrx32*)d, (GBgra32*)s, x);
	else
		GRop32To24((GBgrx32*)d, (GBgra32*)s, x);
	break;
case JointCs(CsBgrx32, CsArgb32):
	if (Composite)
		GComposite32To24((GBgrx32*)d, (GArgb32*)s, x);
	else
		GRop32To24((GBgrx32*)d, (GArgb32*)s, x);
	break;
case JointCs(CsBgrx32, CsAbgr32):
	if (Composite)
		GComposite32To24((GBgrx32*)d, (GAbgr32*)s, x);
	else
		GRop32To24((GBgrx32*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsBgrx32, CsBgr48):
	GRop48To24((GBgrx32*)d, (GBgr48*)s, x);
	break;
case JointCs(CsBgrx32, CsRgb48):
	GRop48To24((GBgrx32*)d, (GRgb48*)s, x);
	break;
case JointCs(CsBgrx32, CsBgra64):
	if (Composite)
		GComposite64To24((GBgrx32*)d, (GBgra64*)s, x);
	else
		GRop64To24((GBgrx32*)d, (GBgra64*)s, x);
	break;
case JointCs(CsBgrx32, CsRgba64):
	if (Composite)
		GComposite64To24((GBgrx32*)d, (GRgba64*)s, x);
	else
		GRop64To24((GBgrx32*)d, (GRgba64*)s, x);
	break;
case JointCs(CsBgrx32, CsAbgr64):
	if (Composite)
		GComposite64To24((GBgrx32*)d, (GAbgr64*)s, x);
	else
		GRop64To24((GBgrx32*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsBgrx32, CsArgb64):
	if (Composite)
		GComposite64To24((GBgrx32*)d, (GArgb64*)s, x);
	else
		GRop64To24((GBgrx32*)d, (GArgb64*)s, x);
	break;
case JointCs(CsXrgb32, CsArgb15):
	if (Composite)
		GComposite15To24((GXrgb32*)d, (GArgb15*)s, x);
	else
		GRop15To24((GXrgb32*)d, (GArgb15*)s, x);
	break;
case JointCs(CsXrgb32, CsRgb15):
	GRop15To24((GXrgb32*)d, (GRgb15*)s, x);
	break;
case JointCs(CsXrgb32, CsAbgr15):
	if (Composite)
		GComposite15To24((GXrgb32*)d, (GAbgr15*)s, x);
	else
		GRop15To24((GXrgb32*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsXrgb32, CsBgr15):
	GRop15To24((GXrgb32*)d, (GBgr15*)s, x);
	break;
case JointCs(CsXrgb32, CsRgb16):
	GRop16To24((GXrgb32*)d, (GRgb16*)s, x);
	break;
case JointCs(CsXrgb32, CsBgr16):
	GRop16To24((GXrgb32*)d, (GBgr16*)s, x);
	break;
case JointCs(CsXrgb32, CsRgb24):
	GRop24To24((GXrgb32*)d, (GRgb24*)s, x);
	break;
case JointCs(CsXrgb32, CsBgr24):
	GRop24To24((GXrgb32*)d, (GBgr24*)s, x);
	break;
case JointCs(CsXrgb32, CsRgbx32):
	GRop24To24((GXrgb32*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsXrgb32, CsBgrx32):
	GRop24To24((GXrgb32*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsXrgb32, CsXrgb32):
	GRop24To24((GXrgb32*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsXrgb32, CsXbgr32):
	GRop24To24((GXrgb32*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsXrgb32, CsRgba32):
	if (Composite)
		GComposite32To24((GXrgb32*)d, (GRgba32*)s, x);
	else
		GRop32To24((GXrgb32*)d, (GRgba32*)s, x);
	break;
case JointCs(CsXrgb32, CsBgra32):
	if (Composite)
		GComposite32To24((GXrgb32*)d, (GBgra32*)s, x);
	else
		GRop32To24((GXrgb32*)d, (GBgra32*)s, x);
	break;
case JointCs(CsXrgb32, CsArgb32):
	if (Composite)
		GComposite32To24((GXrgb32*)d, (GArgb32*)s, x);
	else
		GRop32To24((GXrgb32*)d, (GArgb32*)s, x);
	break;
case JointCs(CsXrgb32, CsAbgr32):
	if (Composite)
		GComposite32To24((GXrgb32*)d, (GAbgr32*)s, x);
	else
		GRop32To24((GXrgb32*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsXrgb32, CsBgr48):
	GRop48To24((GXrgb32*)d, (GBgr48*)s, x);
	break;
case JointCs(CsXrgb32, CsRgb48):
	GRop48To24((GXrgb32*)d, (GRgb48*)s, x);
	break;
case JointCs(CsXrgb32, CsBgra64):
	if (Composite)
		GComposite64To24((GXrgb32*)d, (GBgra64*)s, x);
	else
		GRop64To24((GXrgb32*)d, (GBgra64*)s, x);
	break;
case JointCs(CsXrgb32, CsRgba64):
	if (Composite)
		GComposite64To24((GXrgb32*)d, (GRgba64*)s, x);
	else
		GRop64To24((GXrgb32*)d, (GRgba64*)s, x);
	break;
case JointCs(CsXrgb32, CsAbgr64):
	if (Composite)
		GComposite64To24((GXrgb32*)d, (GAbgr64*)s, x);
	else
		GRop64To24((GXrgb32*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsXrgb32, CsArgb64):
	if (Composite)
		GComposite64To24((GXrgb32*)d, (GArgb64*)s, x);
	else
		GRop64To24((GXrgb32*)d, (GArgb64*)s, x);
	break;
case JointCs(CsXbgr32, CsArgb15):
	if (Composite)
		GComposite15To24((GXbgr32*)d, (GArgb15*)s, x);
	else
		GRop15To24((GXbgr32*)d, (GArgb15*)s, x);
	break;
case JointCs(CsXbgr32, CsRgb15):
	GRop15To24((GXbgr32*)d, (GRgb15*)s, x);
	break;
case JointCs(CsXbgr32, CsAbgr15):
	if (Composite)
		GComposite15To24((GXbgr32*)d, (GAbgr15*)s, x);
	else
		GRop15To24((GXbgr32*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsXbgr32, CsBgr15):
	GRop15To24((GXbgr32*)d, (GBgr15*)s, x);
	break;
case JointCs(CsXbgr32, CsRgb16):
	GRop16To24((GXbgr32*)d, (GRgb16*)s, x);
	break;
case JointCs(CsXbgr32, CsBgr16):
	GRop16To24((GXbgr32*)d, (GBgr16*)s, x);
	break;
case JointCs(CsXbgr32, CsRgb24):
	GRop24To24((GXbgr32*)d, (GRgb24*)s, x);
	break;
case JointCs(CsXbgr32, CsBgr24):
	GRop24To24((GXbgr32*)d, (GBgr24*)s, x);
	break;
case JointCs(CsXbgr32, CsRgbx32):
	GRop24To24((GXbgr32*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsXbgr32, CsBgrx32):
	GRop24To24((GXbgr32*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsXbgr32, CsXrgb32):
	GRop24To24((GXbgr32*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsXbgr32, CsXbgr32):
	GRop24To24((GXbgr32*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsXbgr32, CsRgba32):
	if (Composite)
		GComposite32To24((GXbgr32*)d, (GRgba32*)s, x);
	else
		GRop32To24((GXbgr32*)d, (GRgba32*)s, x);
	break;
case JointCs(CsXbgr32, CsBgra32):
	if (Composite)
		GComposite32To24((GXbgr32*)d, (GBgra32*)s, x);
	else
		GRop32To24((GXbgr32*)d, (GBgra32*)s, x);
	break;
case JointCs(CsXbgr32, CsArgb32):
	if (Composite)
		GComposite32To24((GXbgr32*)d, (GArgb32*)s, x);
	else
		GRop32To24((GXbgr32*)d, (GArgb32*)s, x);
	break;
case JointCs(CsXbgr32, CsAbgr32):
	if (Composite)
		GComposite32To24((GXbgr32*)d, (GAbgr32*)s, x);
	else
		GRop32To24((GXbgr32*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsXbgr32, CsBgr48):
	GRop48To24((GXbgr32*)d, (GBgr48*)s, x);
	break;
case JointCs(CsXbgr32, CsRgb48):
	GRop48To24((GXbgr32*)d, (GRgb48*)s, x);
	break;
case JointCs(CsXbgr32, CsBgra64):
	if (Composite)
		GComposite64To24((GXbgr32*)d, (GBgra64*)s, x);
	else
		GRop64To24((GXbgr32*)d, (GBgra64*)s, x);
	break;
case JointCs(CsXbgr32, CsRgba64):
	if (Composite)
		GComposite64To24((GXbgr32*)d, (GRgba64*)s, x);
	else
		GRop64To24((GXbgr32*)d, (GRgba64*)s, x);
	break;
case JointCs(CsXbgr32, CsAbgr64):
	if (Composite)
		GComposite64To24((GXbgr32*)d, (GAbgr64*)s, x);
	else
		GRop64To24((GXbgr32*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsXbgr32, CsArgb64):
	if (Composite)
		GComposite64To24((GXbgr32*)d, (GArgb64*)s, x);
	else
		GRop64To24((GXbgr32*)d, (GArgb64*)s, x);
	break;
case JointCs(CsRgba32, CsArgb15):
	if (Composite)
		GComposite15To32((GRgba32*)d, (GArgb15*)s, x);
	else
		GRop15To32((GRgba32*)d, (GArgb15*)s, x);
	break;
case JointCs(CsRgba32, CsRgb15):
	GRop15To32((GRgba32*)d, (GRgb15*)s, x);
	break;
case JointCs(CsRgba32, CsAbgr15):
	if (Composite)
		GComposite15To32((GRgba32*)d, (GAbgr15*)s, x);
	else
		GRop15To32((GRgba32*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsRgba32, CsBgr15):
	GRop15To32((GRgba32*)d, (GBgr15*)s, x);
	break;
case JointCs(CsRgba32, CsRgb16):
	GRop16To32((GRgba32*)d, (GRgb16*)s, x);
	break;
case JointCs(CsRgba32, CsBgr16):
	GRop16To32((GRgba32*)d, (GBgr16*)s, x);
	break;
case JointCs(CsRgba32, CsRgb24):
	GRop24To32((GRgba32*)d, (GRgb24*)s, x);
	break;
case JointCs(CsRgba32, CsBgr24):
	GRop24To32((GRgba32*)d, (GBgr24*)s, x);
	break;
case JointCs(CsRgba32, CsRgbx32):
	GRop24To32((GRgba32*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsRgba32, CsBgrx32):
	GRop24To32((GRgba32*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsRgba32, CsXrgb32):
	GRop24To32((GRgba32*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsRgba32, CsXbgr32):
	GRop24To32((GRgba32*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsRgba32, CsRgba32):
	if (Composite)
		GComposite32To32((GRgba32*)d, (GRgba32*)s, x);
	else
		GRop32To32((GRgba32*)d, (GRgba32*)s, x);
	break;
case JointCs(CsRgba32, CsBgra32):
	if (Composite)
		GComposite32To32((GRgba32*)d, (GBgra32*)s, x);
	else
		GRop32To32((GRgba32*)d, (GBgra32*)s, x);
	break;
case JointCs(CsRgba32, CsArgb32):
	if (Composite)
		GComposite32To32((GRgba32*)d, (GArgb32*)s, x);
	else
		GRop32To32((GRgba32*)d, (GArgb32*)s, x);
	break;
case JointCs(CsRgba32, CsAbgr32):
	if (Composite)
		GComposite32To32((GRgba32*)d, (GAbgr32*)s, x);
	else
		GRop32To32((GRgba32*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsRgba32, CsBgr48):
	GRop48To32((GRgba32*)d, (GBgr48*)s, x);
	break;
case JointCs(CsRgba32, CsRgb48):
	GRop48To32((GRgba32*)d, (GRgb48*)s, x);
	break;
case JointCs(CsRgba32, CsBgra64):
	if (Composite)
		GComposite64To32((GRgba32*)d, (GBgra64*)s, x);
	else
		GRop64To32((GRgba32*)d, (GBgra64*)s, x);
	break;
case JointCs(CsRgba32, CsRgba64):
	if (Composite)
		GComposite64To32((GRgba32*)d, (GRgba64*)s, x);
	else
		GRop64To32((GRgba32*)d, (GRgba64*)s, x);
	break;
case JointCs(CsRgba32, CsAbgr64):
	if (Composite)
		GComposite64To32((GRgba32*)d, (GAbgr64*)s, x);
	else
		GRop64To32((GRgba32*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsRgba32, CsArgb64):
	if (Composite)
		GComposite64To32((GRgba32*)d, (GArgb64*)s, x);
	else
		GRop64To32((GRgba32*)d, (GArgb64*)s, x);
	break;
case JointCs(CsBgra32, CsArgb15):
	if (Composite)
		GComposite15To32((GBgra32*)d, (GArgb15*)s, x);
	else
		GRop15To32((GBgra32*)d, (GArgb15*)s, x);
	break;
case JointCs(CsBgra32, CsRgb15):
	GRop15To32((GBgra32*)d, (GRgb15*)s, x);
	break;
case JointCs(CsBgra32, CsAbgr15):
	if (Composite)
		GComposite15To32((GBgra32*)d, (GAbgr15*)s, x);
	else
		GRop15To32((GBgra32*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsBgra32, CsBgr15):
	GRop15To32((GBgra32*)d, (GBgr15*)s, x);
	break;
case JointCs(CsBgra32, CsRgb16):
	GRop16To32((GBgra32*)d, (GRgb16*)s, x);
	break;
case JointCs(CsBgra32, CsBgr16):
	GRop16To32((GBgra32*)d, (GBgr16*)s, x);
	break;
case JointCs(CsBgra32, CsRgb24):
	GRop24To32((GBgra32*)d, (GRgb24*)s, x);
	break;
case JointCs(CsBgra32, CsBgr24):
	GRop24To32((GBgra32*)d, (GBgr24*)s, x);
	break;
case JointCs(CsBgra32, CsRgbx32):
	GRop24To32((GBgra32*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsBgra32, CsBgrx32):
	GRop24To32((GBgra32*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsBgra32, CsXrgb32):
	GRop24To32((GBgra32*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsBgra32, CsXbgr32):
	GRop24To32((GBgra32*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsBgra32, CsRgba32):
	if (Composite)
		GComposite32To32((GBgra32*)d, (GRgba32*)s, x);
	else
		GRop32To32((GBgra32*)d, (GRgba32*)s, x);
	break;
case JointCs(CsBgra32, CsBgra32):
	if (Composite)
		GComposite32To32((GBgra32*)d, (GBgra32*)s, x);
	else
		GRop32To32((GBgra32*)d, (GBgra32*)s, x);
	break;
case JointCs(CsBgra32, CsArgb32):
	if (Composite)
		GComposite32To32((GBgra32*)d, (GArgb32*)s, x);
	else
		GRop32To32((GBgra32*)d, (GArgb32*)s, x);
	break;
case JointCs(CsBgra32, CsAbgr32):
	if (Composite)
		GComposite32To32((GBgra32*)d, (GAbgr32*)s, x);
	else
		GRop32To32((GBgra32*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsBgra32, CsBgr48):
	GRop48To32((GBgra32*)d, (GBgr48*)s, x);
	break;
case JointCs(CsBgra32, CsRgb48):
	GRop48To32((GBgra32*)d, (GRgb48*)s, x);
	break;
case JointCs(CsBgra32, CsBgra64):
	if (Composite)
		GComposite64To32((GBgra32*)d, (GBgra64*)s, x);
	else
		GRop64To32((GBgra32*)d, (GBgra64*)s, x);
	break;
case JointCs(CsBgra32, CsRgba64):
	if (Composite)
		GComposite64To32((GBgra32*)d, (GRgba64*)s, x);
	else
		GRop64To32((GBgra32*)d, (GRgba64*)s, x);
	break;
case JointCs(CsBgra32, CsAbgr64):
	if (Composite)
		GComposite64To32((GBgra32*)d, (GAbgr64*)s, x);
	else
		GRop64To32((GBgra32*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsBgra32, CsArgb64):
	if (Composite)
		GComposite64To32((GBgra32*)d, (GArgb64*)s, x);
	else
		GRop64To32((GBgra32*)d, (GArgb64*)s, x);
	break;
case JointCs(CsArgb32, CsArgb15):
	if (Composite)
		GComposite15To32((GArgb32*)d, (GArgb15*)s, x);
	else
		GRop15To32((GArgb32*)d, (GArgb15*)s, x);
	break;
case JointCs(CsArgb32, CsRgb15):
	GRop15To32((GArgb32*)d, (GRgb15*)s, x);
	break;
case JointCs(CsArgb32, CsAbgr15):
	if (Composite)
		GComposite15To32((GArgb32*)d, (GAbgr15*)s, x);
	else
		GRop15To32((GArgb32*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsArgb32, CsBgr15):
	GRop15To32((GArgb32*)d, (GBgr15*)s, x);
	break;
case JointCs(CsArgb32, CsRgb16):
	GRop16To32((GArgb32*)d, (GRgb16*)s, x);
	break;
case JointCs(CsArgb32, CsBgr16):
	GRop16To32((GArgb32*)d, (GBgr16*)s, x);
	break;
case JointCs(CsArgb32, CsRgb24):
	GRop24To32((GArgb32*)d, (GRgb24*)s, x);
	break;
case JointCs(CsArgb32, CsBgr24):
	GRop24To32((GArgb32*)d, (GBgr24*)s, x);
	break;
case JointCs(CsArgb32, CsRgbx32):
	GRop24To32((GArgb32*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsArgb32, CsBgrx32):
	GRop24To32((GArgb32*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsArgb32, CsXrgb32):
	GRop24To32((GArgb32*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsArgb32, CsXbgr32):
	GRop24To32((GArgb32*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsArgb32, CsRgba32):
	if (Composite)
		GComposite32To32((GArgb32*)d, (GRgba32*)s, x);
	else
		GRop32To32((GArgb32*)d, (GRgba32*)s, x);
	break;
case JointCs(CsArgb32, CsBgra32):
	if (Composite)
		GComposite32To32((GArgb32*)d, (GBgra32*)s, x);
	else
		GRop32To32((GArgb32*)d, (GBgra32*)s, x);
	break;
case JointCs(CsArgb32, CsArgb32):
	if (Composite)
		GComposite32To32((GArgb32*)d, (GArgb32*)s, x);
	else
		GRop32To32((GArgb32*)d, (GArgb32*)s, x);
	break;
case JointCs(CsArgb32, CsAbgr32):
	if (Composite)
		GComposite32To32((GArgb32*)d, (GAbgr32*)s, x);
	else
		GRop32To32((GArgb32*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsArgb32, CsBgr48):
	GRop48To32((GArgb32*)d, (GBgr48*)s, x);
	break;
case JointCs(CsArgb32, CsRgb48):
	GRop48To32((GArgb32*)d, (GRgb48*)s, x);
	break;
case JointCs(CsArgb32, CsBgra64):
	if (Composite)
		GComposite64To32((GArgb32*)d, (GBgra64*)s, x);
	else
		GRop64To32((GArgb32*)d, (GBgra64*)s, x);
	break;
case JointCs(CsArgb32, CsRgba64):
	if (Composite)
		GComposite64To32((GArgb32*)d, (GRgba64*)s, x);
	else
		GRop64To32((GArgb32*)d, (GRgba64*)s, x);
	break;
case JointCs(CsArgb32, CsAbgr64):
	if (Composite)
		GComposite64To32((GArgb32*)d, (GAbgr64*)s, x);
	else
		GRop64To32((GArgb32*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsArgb32, CsArgb64):
	if (Composite)
		GComposite64To32((GArgb32*)d, (GArgb64*)s, x);
	else
		GRop64To32((GArgb32*)d, (GArgb64*)s, x);
	break;
case JointCs(CsAbgr32, CsArgb15):
	if (Composite)
		GComposite15To32((GAbgr32*)d, (GArgb15*)s, x);
	else
		GRop15To32((GAbgr32*)d, (GArgb15*)s, x);
	break;
case JointCs(CsAbgr32, CsRgb15):
	GRop15To32((GAbgr32*)d, (GRgb15*)s, x);
	break;
case JointCs(CsAbgr32, CsAbgr15):
	if (Composite)
		GComposite15To32((GAbgr32*)d, (GAbgr15*)s, x);
	else
		GRop15To32((GAbgr32*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsAbgr32, CsBgr15):
	GRop15To32((GAbgr32*)d, (GBgr15*)s, x);
	break;
case JointCs(CsAbgr32, CsRgb16):
	GRop16To32((GAbgr32*)d, (GRgb16*)s, x);
	break;
case JointCs(CsAbgr32, CsBgr16):
	GRop16To32((GAbgr32*)d, (GBgr16*)s, x);
	break;
case JointCs(CsAbgr32, CsRgb24):
	GRop24To32((GAbgr32*)d, (GRgb24*)s, x);
	break;
case JointCs(CsAbgr32, CsBgr24):
	GRop24To32((GAbgr32*)d, (GBgr24*)s, x);
	break;
case JointCs(CsAbgr32, CsRgbx32):
	GRop24To32((GAbgr32*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsAbgr32, CsBgrx32):
	GRop24To32((GAbgr32*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsAbgr32, CsXrgb32):
	GRop24To32((GAbgr32*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsAbgr32, CsXbgr32):
	GRop24To32((GAbgr32*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsAbgr32, CsRgba32):
	if (Composite)
		GComposite32To32((GAbgr32*)d, (GRgba32*)s, x);
	else
		GRop32To32((GAbgr32*)d, (GRgba32*)s, x);
	break;
case JointCs(CsAbgr32, CsBgra32):
	if (Composite)
		GComposite32To32((GAbgr32*)d, (GBgra32*)s, x);
	else
		GRop32To32((GAbgr32*)d, (GBgra32*)s, x);
	break;
case JointCs(CsAbgr32, CsArgb32):
	if (Composite)
		GComposite32To32((GAbgr32*)d, (GArgb32*)s, x);
	else
		GRop32To32((GAbgr32*)d, (GArgb32*)s, x);
	break;
case JointCs(CsAbgr32, CsAbgr32):
	if (Composite)
		GComposite32To32((GAbgr32*)d, (GAbgr32*)s, x);
	else
		GRop32To32((GAbgr32*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsAbgr32, CsBgr48):
	GRop48To32((GAbgr32*)d, (GBgr48*)s, x);
	break;
case JointCs(CsAbgr32, CsRgb48):
	GRop48To32((GAbgr32*)d, (GRgb48*)s, x);
	break;
case JointCs(CsAbgr32, CsBgra64):
	if (Composite)
		GComposite64To32((GAbgr32*)d, (GBgra64*)s, x);
	else
		GRop64To32((GAbgr32*)d, (GBgra64*)s, x);
	break;
case JointCs(CsAbgr32, CsRgba64):
	if (Composite)
		GComposite64To32((GAbgr32*)d, (GRgba64*)s, x);
	else
		GRop64To32((GAbgr32*)d, (GRgba64*)s, x);
	break;
case JointCs(CsAbgr32, CsAbgr64):
	if (Composite)
		GComposite64To32((GAbgr32*)d, (GAbgr64*)s, x);
	else
		GRop64To32((GAbgr32*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsAbgr32, CsArgb64):
	if (Composite)
		GComposite64To32((GAbgr32*)d, (GArgb64*)s, x);
	else
		GRop64To32((GAbgr32*)d, (GArgb64*)s, x);
	break;
case JointCs(CsBgr48, CsArgb15):
	if (Composite)
		GComposite15To48((GBgr48*)d, (GArgb15*)s, x);
	else
		GRop15To48((GBgr48*)d, (GArgb15*)s, x);
	break;
case JointCs(CsBgr48, CsRgb15):
	GRop15To48((GBgr48*)d, (GRgb15*)s, x);
	break;
case JointCs(CsBgr48, CsAbgr15):
	if (Composite)
		GComposite15To48((GBgr48*)d, (GAbgr15*)s, x);
	else
		GRop15To48((GBgr48*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsBgr48, CsBgr15):
	GRop15To48((GBgr48*)d, (GBgr15*)s, x);
	break;
case JointCs(CsBgr48, CsRgb16):
	GRop16To48((GBgr48*)d, (GRgb16*)s, x);
	break;
case JointCs(CsBgr48, CsBgr16):
	GRop16To48((GBgr48*)d, (GBgr16*)s, x);
	break;
case JointCs(CsBgr48, CsRgb24):
	GRop24To48((GBgr48*)d, (GRgb24*)s, x);
	break;
case JointCs(CsBgr48, CsBgr24):
	GRop24To48((GBgr48*)d, (GBgr24*)s, x);
	break;
case JointCs(CsBgr48, CsRgbx32):
	GRop24To48((GBgr48*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsBgr48, CsBgrx32):
	GRop24To48((GBgr48*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsBgr48, CsXrgb32):
	GRop24To48((GBgr48*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsBgr48, CsXbgr32):
	GRop24To48((GBgr48*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsBgr48, CsRgba32):
	if (Composite)
		GComposite32To48((GBgr48*)d, (GRgba32*)s, x);
	else
		GRop32To48((GBgr48*)d, (GRgba32*)s, x);
	break;
case JointCs(CsBgr48, CsBgra32):
	if (Composite)
		GComposite32To48((GBgr48*)d, (GBgra32*)s, x);
	else
		GRop32To48((GBgr48*)d, (GBgra32*)s, x);
	break;
case JointCs(CsBgr48, CsArgb32):
	if (Composite)
		GComposite32To48((GBgr48*)d, (GArgb32*)s, x);
	else
		GRop32To48((GBgr48*)d, (GArgb32*)s, x);
	break;
case JointCs(CsBgr48, CsAbgr32):
	if (Composite)
		GComposite32To48((GBgr48*)d, (GAbgr32*)s, x);
	else
		GRop32To48((GBgr48*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsBgr48, CsBgr48):
	GRop48To48((GBgr48*)d, (GBgr48*)s, x);
	break;
case JointCs(CsBgr48, CsRgb48):
	GRop48To48((GBgr48*)d, (GRgb48*)s, x);
	break;
case JointCs(CsBgr48, CsBgra64):
	if (Composite)
		GComposite64To48((GBgr48*)d, (GBgra64*)s, x);
	else
		GRop64To48((GBgr48*)d, (GBgra64*)s, x);
	break;
case JointCs(CsBgr48, CsRgba64):
	if (Composite)
		GComposite64To48((GBgr48*)d, (GRgba64*)s, x);
	else
		GRop64To48((GBgr48*)d, (GRgba64*)s, x);
	break;
case JointCs(CsBgr48, CsAbgr64):
	if (Composite)
		GComposite64To48((GBgr48*)d, (GAbgr64*)s, x);
	else
		GRop64To48((GBgr48*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsBgr48, CsArgb64):
	if (Composite)
		GComposite64To48((GBgr48*)d, (GArgb64*)s, x);
	else
		GRop64To48((GBgr48*)d, (GArgb64*)s, x);
	break;
case JointCs(CsRgb48, CsArgb15):
	if (Composite)
		GComposite15To48((GRgb48*)d, (GArgb15*)s, x);
	else
		GRop15To48((GRgb48*)d, (GArgb15*)s, x);
	break;
case JointCs(CsRgb48, CsRgb15):
	GRop15To48((GRgb48*)d, (GRgb15*)s, x);
	break;
case JointCs(CsRgb48, CsAbgr15):
	if (Composite)
		GComposite15To48((GRgb48*)d, (GAbgr15*)s, x);
	else
		GRop15To48((GRgb48*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsRgb48, CsBgr15):
	GRop15To48((GRgb48*)d, (GBgr15*)s, x);
	break;
case JointCs(CsRgb48, CsRgb16):
	GRop16To48((GRgb48*)d, (GRgb16*)s, x);
	break;
case JointCs(CsRgb48, CsBgr16):
	GRop16To48((GRgb48*)d, (GBgr16*)s, x);
	break;
case JointCs(CsRgb48, CsRgb24):
	GRop24To48((GRgb48*)d, (GRgb24*)s, x);
	break;
case JointCs(CsRgb48, CsBgr24):
	GRop24To48((GRgb48*)d, (GBgr24*)s, x);
	break;
case JointCs(CsRgb48, CsRgbx32):
	GRop24To48((GRgb48*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsRgb48, CsBgrx32):
	GRop24To48((GRgb48*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsRgb48, CsXrgb32):
	GRop24To48((GRgb48*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsRgb48, CsXbgr32):
	GRop24To48((GRgb48*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsRgb48, CsRgba32):
	if (Composite)
		GComposite32To48((GRgb48*)d, (GRgba32*)s, x);
	else
		GRop32To48((GRgb48*)d, (GRgba32*)s, x);
	break;
case JointCs(CsRgb48, CsBgra32):
	if (Composite)
		GComposite32To48((GRgb48*)d, (GBgra32*)s, x);
	else
		GRop32To48((GRgb48*)d, (GBgra32*)s, x);
	break;
case JointCs(CsRgb48, CsArgb32):
	if (Composite)
		GComposite32To48((GRgb48*)d, (GArgb32*)s, x);
	else
		GRop32To48((GRgb48*)d, (GArgb32*)s, x);
	break;
case JointCs(CsRgb48, CsAbgr32):
	if (Composite)
		GComposite32To48((GRgb48*)d, (GAbgr32*)s, x);
	else
		GRop32To48((GRgb48*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsRgb48, CsBgr48):
	GRop48To48((GRgb48*)d, (GBgr48*)s, x);
	break;
case JointCs(CsRgb48, CsRgb48):
	GRop48To48((GRgb48*)d, (GRgb48*)s, x);
	break;
case JointCs(CsRgb48, CsBgra64):
	if (Composite)
		GComposite64To48((GRgb48*)d, (GBgra64*)s, x);
	else
		GRop64To48((GRgb48*)d, (GBgra64*)s, x);
	break;
case JointCs(CsRgb48, CsRgba64):
	if (Composite)
		GComposite64To48((GRgb48*)d, (GRgba64*)s, x);
	else
		GRop64To48((GRgb48*)d, (GRgba64*)s, x);
	break;
case JointCs(CsRgb48, CsAbgr64):
	if (Composite)
		GComposite64To48((GRgb48*)d, (GAbgr64*)s, x);
	else
		GRop64To48((GRgb48*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsRgb48, CsArgb64):
	if (Composite)
		GComposite64To48((GRgb48*)d, (GArgb64*)s, x);
	else
		GRop64To48((GRgb48*)d, (GArgb64*)s, x);
	break;
case JointCs(CsBgra64, CsArgb15):
	if (Composite)
		GComposite15To64((GBgra64*)d, (GArgb15*)s, x);
	else
		GRop15To64((GBgra64*)d, (GArgb15*)s, x);
	break;
case JointCs(CsBgra64, CsRgb15):
	GRop15To64((GBgra64*)d, (GRgb15*)s, x);
	break;
case JointCs(CsBgra64, CsAbgr15):
	if (Composite)
		GComposite15To64((GBgra64*)d, (GAbgr15*)s, x);
	else
		GRop15To64((GBgra64*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsBgra64, CsBgr15):
	GRop15To64((GBgra64*)d, (GBgr15*)s, x);
	break;
case JointCs(CsBgra64, CsRgb16):
	GRop16To64((GBgra64*)d, (GRgb16*)s, x);
	break;
case JointCs(CsBgra64, CsBgr16):
	GRop16To64((GBgra64*)d, (GBgr16*)s, x);
	break;
case JointCs(CsBgra64, CsRgb24):
	GRop24To64((GBgra64*)d, (GRgb24*)s, x);
	break;
case JointCs(CsBgra64, CsBgr24):
	GRop24To64((GBgra64*)d, (GBgr24*)s, x);
	break;
case JointCs(CsBgra64, CsRgbx32):
	GRop24To64((GBgra64*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsBgra64, CsBgrx32):
	GRop24To64((GBgra64*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsBgra64, CsXrgb32):
	GRop24To64((GBgra64*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsBgra64, CsXbgr32):
	GRop24To64((GBgra64*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsBgra64, CsRgba32):
	if (Composite)
		GComposite32To64((GBgra64*)d, (GRgba32*)s, x);
	else
		GRop32To64((GBgra64*)d, (GRgba32*)s, x);
	break;
case JointCs(CsBgra64, CsBgra32):
	if (Composite)
		GComposite32To64((GBgra64*)d, (GBgra32*)s, x);
	else
		GRop32To64((GBgra64*)d, (GBgra32*)s, x);
	break;
case JointCs(CsBgra64, CsArgb32):
	if (Composite)
		GComposite32To64((GBgra64*)d, (GArgb32*)s, x);
	else
		GRop32To64((GBgra64*)d, (GArgb32*)s, x);
	break;
case JointCs(CsBgra64, CsAbgr32):
	if (Composite)
		GComposite32To64((GBgra64*)d, (GAbgr32*)s, x);
	else
		GRop32To64((GBgra64*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsBgra64, CsBgr48):
	GRop48To64((GBgra64*)d, (GBgr48*)s, x);
	break;
case JointCs(CsBgra64, CsRgb48):
	GRop48To64((GBgra64*)d, (GRgb48*)s, x);
	break;
case JointCs(CsBgra64, CsBgra64):
	if (Composite)
		GComposite64To64((GBgra64*)d, (GBgra64*)s, x);
	else
		GRop64To64((GBgra64*)d, (GBgra64*)s, x);
	break;
case JointCs(CsBgra64, CsRgba64):
	if (Composite)
		GComposite64To64((GBgra64*)d, (GRgba64*)s, x);
	else
		GRop64To64((GBgra64*)d, (GRgba64*)s, x);
	break;
case JointCs(CsBgra64, CsAbgr64):
	if (Composite)
		GComposite64To64((GBgra64*)d, (GAbgr64*)s, x);
	else
		GRop64To64((GBgra64*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsBgra64, CsArgb64):
	if (Composite)
		GComposite64To64((GBgra64*)d, (GArgb64*)s, x);
	else
		GRop64To64((GBgra64*)d, (GArgb64*)s, x);
	break;
case JointCs(CsRgba64, CsArgb15):
	if (Composite)
		GComposite15To64((GRgba64*)d, (GArgb15*)s, x);
	else
		GRop15To64((GRgba64*)d, (GArgb15*)s, x);
	break;
case JointCs(CsRgba64, CsRgb15):
	GRop15To64((GRgba64*)d, (GRgb15*)s, x);
	break;
case JointCs(CsRgba64, CsAbgr15):
	if (Composite)
		GComposite15To64((GRgba64*)d, (GAbgr15*)s, x);
	else
		GRop15To64((GRgba64*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsRgba64, CsBgr15):
	GRop15To64((GRgba64*)d, (GBgr15*)s, x);
	break;
case JointCs(CsRgba64, CsRgb16):
	GRop16To64((GRgba64*)d, (GRgb16*)s, x);
	break;
case JointCs(CsRgba64, CsBgr16):
	GRop16To64((GRgba64*)d, (GBgr16*)s, x);
	break;
case JointCs(CsRgba64, CsRgb24):
	GRop24To64((GRgba64*)d, (GRgb24*)s, x);
	break;
case JointCs(CsRgba64, CsBgr24):
	GRop24To64((GRgba64*)d, (GBgr24*)s, x);
	break;
case JointCs(CsRgba64, CsRgbx32):
	GRop24To64((GRgba64*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsRgba64, CsBgrx32):
	GRop24To64((GRgba64*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsRgba64, CsXrgb32):
	GRop24To64((GRgba64*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsRgba64, CsXbgr32):
	GRop24To64((GRgba64*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsRgba64, CsRgba32):
	if (Composite)
		GComposite32To64((GRgba64*)d, (GRgba32*)s, x);
	else
		GRop32To64((GRgba64*)d, (GRgba32*)s, x);
	break;
case JointCs(CsRgba64, CsBgra32):
	if (Composite)
		GComposite32To64((GRgba64*)d, (GBgra32*)s, x);
	else
		GRop32To64((GRgba64*)d, (GBgra32*)s, x);
	break;
case JointCs(CsRgba64, CsArgb32):
	if (Composite)
		GComposite32To64((GRgba64*)d, (GArgb32*)s, x);
	else
		GRop32To64((GRgba64*)d, (GArgb32*)s, x);
	break;
case JointCs(CsRgba64, CsAbgr32):
	if (Composite)
		GComposite32To64((GRgba64*)d, (GAbgr32*)s, x);
	else
		GRop32To64((GRgba64*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsRgba64, CsBgr48):
	GRop48To64((GRgba64*)d, (GBgr48*)s, x);
	break;
case JointCs(CsRgba64, CsRgb48):
	GRop48To64((GRgba64*)d, (GRgb48*)s, x);
	break;
case JointCs(CsRgba64, CsBgra64):
	if (Composite)
		GComposite64To64((GRgba64*)d, (GBgra64*)s, x);
	else
		GRop64To64((GRgba64*)d, (GBgra64*)s, x);
	break;
case JointCs(CsRgba64, CsRgba64):
	if (Composite)
		GComposite64To64((GRgba64*)d, (GRgba64*)s, x);
	else
		GRop64To64((GRgba64*)d, (GRgba64*)s, x);
	break;
case JointCs(CsRgba64, CsAbgr64):
	if (Composite)
		GComposite64To64((GRgba64*)d, (GAbgr64*)s, x);
	else
		GRop64To64((GRgba64*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsRgba64, CsArgb64):
	if (Composite)
		GComposite64To64((GRgba64*)d, (GArgb64*)s, x);
	else
		GRop64To64((GRgba64*)d, (GArgb64*)s, x);
	break;
case JointCs(CsAbgr64, CsArgb15):
	if (Composite)
		GComposite15To64((GAbgr64*)d, (GArgb15*)s, x);
	else
		GRop15To64((GAbgr64*)d, (GArgb15*)s, x);
	break;
case JointCs(CsAbgr64, CsRgb15):
	GRop15To64((GAbgr64*)d, (GRgb15*)s, x);
	break;
case JointCs(CsAbgr64, CsAbgr15):
	if (Composite)
		GComposite15To64((GAbgr64*)d, (GAbgr15*)s, x);
	else
		GRop15To64((GAbgr64*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsAbgr64, CsBgr15):
	GRop15To64((GAbgr64*)d, (GBgr15*)s, x);
	break;
case JointCs(CsAbgr64, CsRgb16):
	GRop16To64((GAbgr64*)d, (GRgb16*)s, x);
	break;
case JointCs(CsAbgr64, CsBgr16):
	GRop16To64((GAbgr64*)d, (GBgr16*)s, x);
	break;
case JointCs(CsAbgr64, CsRgb24):
	GRop24To64((GAbgr64*)d, (GRgb24*)s, x);
	break;
case JointCs(CsAbgr64, CsBgr24):
	GRop24To64((GAbgr64*)d, (GBgr24*)s, x);
	break;
case JointCs(CsAbgr64, CsRgbx32):
	GRop24To64((GAbgr64*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsAbgr64, CsBgrx32):
	GRop24To64((GAbgr64*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsAbgr64, CsXrgb32):
	GRop24To64((GAbgr64*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsAbgr64, CsXbgr32):
	GRop24To64((GAbgr64*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsAbgr64, CsRgba32):
	if (Composite)
		GComposite32To64((GAbgr64*)d, (GRgba32*)s, x);
	else
		GRop32To64((GAbgr64*)d, (GRgba32*)s, x);
	break;
case JointCs(CsAbgr64, CsBgra32):
	if (Composite)
		GComposite32To64((GAbgr64*)d, (GBgra32*)s, x);
	else
		GRop32To64((GAbgr64*)d, (GBgra32*)s, x);
	break;
case JointCs(CsAbgr64, CsArgb32):
	if (Composite)
		GComposite32To64((GAbgr64*)d, (GArgb32*)s, x);
	else
		GRop32To64((GAbgr64*)d, (GArgb32*)s, x);
	break;
case JointCs(CsAbgr64, CsAbgr32):
	if (Composite)
		GComposite32To64((GAbgr64*)d, (GAbgr32*)s, x);
	else
		GRop32To64((GAbgr64*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsAbgr64, CsBgr48):
	GRop48To64((GAbgr64*)d, (GBgr48*)s, x);
	break;
case JointCs(CsAbgr64, CsRgb48):
	GRop48To64((GAbgr64*)d, (GRgb48*)s, x);
	break;
case JointCs(CsAbgr64, CsBgra64):
	if (Composite)
		GComposite64To64((GAbgr64*)d, (GBgra64*)s, x);
	else
		GRop64To64((GAbgr64*)d, (GBgra64*)s, x);
	break;
case JointCs(CsAbgr64, CsRgba64):
	if (Composite)
		GComposite64To64((GAbgr64*)d, (GRgba64*)s, x);
	else
		GRop64To64((GAbgr64*)d, (GRgba64*)s, x);
	break;
case JointCs(CsAbgr64, CsAbgr64):
	if (Composite)
		GComposite64To64((GAbgr64*)d, (GAbgr64*)s, x);
	else
		GRop64To64((GAbgr64*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsAbgr64, CsArgb64):
	if (Composite)
		GComposite64To64((GAbgr64*)d, (GArgb64*)s, x);
	else
		GRop64To64((GAbgr64*)d, (GArgb64*)s, x);
	break;
case JointCs(CsArgb64, CsArgb15):
	if (Composite)
		GComposite15To64((GArgb64*)d, (GArgb15*)s, x);
	else
		GRop15To64((GArgb64*)d, (GArgb15*)s, x);
	break;
case JointCs(CsArgb64, CsRgb15):
	GRop15To64((GArgb64*)d, (GRgb15*)s, x);
	break;
case JointCs(CsArgb64, CsAbgr15):
	if (Composite)
		GComposite15To64((GArgb64*)d, (GAbgr15*)s, x);
	else
		GRop15To64((GArgb64*)d, (GAbgr15*)s, x);
	break;
case JointCs(CsArgb64, CsBgr15):
	GRop15To64((GArgb64*)d, (GBgr15*)s, x);
	break;
case JointCs(CsArgb64, CsRgb16):
	GRop16To64((GArgb64*)d, (GRgb16*)s, x);
	break;
case JointCs(CsArgb64, CsBgr16):
	GRop16To64((GArgb64*)d, (GBgr16*)s, x);
	break;
case JointCs(CsArgb64, CsRgb24):
	GRop24To64((GArgb64*)d, (GRgb24*)s, x);
	break;
case JointCs(CsArgb64, CsBgr24):
	GRop24To64((GArgb64*)d, (GBgr24*)s, x);
	break;
case JointCs(CsArgb64, CsRgbx32):
	GRop24To64((GArgb64*)d, (GRgbx32*)s, x);
	break;
case JointCs(CsArgb64, CsBgrx32):
	GRop24To64((GArgb64*)d, (GBgrx32*)s, x);
	break;
case JointCs(CsArgb64, CsXrgb32):
	GRop24To64((GArgb64*)d, (GXrgb32*)s, x);
	break;
case JointCs(CsArgb64, CsXbgr32):
	GRop24To64((GArgb64*)d, (GXbgr32*)s, x);
	break;
case JointCs(CsArgb64, CsRgba32):
	if (Composite)
		GComposite32To64((GArgb64*)d, (GRgba32*)s, x);
	else
		GRop32To64((GArgb64*)d, (GRgba32*)s, x);
	break;
case JointCs(CsArgb64, CsBgra32):
	if (Composite)
		GComposite32To64((GArgb64*)d, (GBgra32*)s, x);
	else
		GRop32To64((GArgb64*)d, (GBgra32*)s, x);
	break;
case JointCs(CsArgb64, CsArgb32):
	if (Composite)
		GComposite32To64((GArgb64*)d, (GArgb32*)s, x);
	else
		GRop32To64((GArgb64*)d, (GArgb32*)s, x);
	break;
case JointCs(CsArgb64, CsAbgr32):
	if (Composite)
		GComposite32To64((GArgb64*)d, (GAbgr32*)s, x);
	else
		GRop32To64((GArgb64*)d, (GAbgr32*)s, x);
	break;
case JointCs(CsArgb64, CsBgr48):
	GRop48To64((GArgb64*)d, (GBgr48*)s, x);
	break;
case JointCs(CsArgb64, CsRgb48):
	GRop48To64((GArgb64*)d, (GRgb48*)s, x);
	break;
case JointCs(CsArgb64, CsBgra64):
	if (Composite)
		GComposite64To64((GArgb64*)d, (GBgra64*)s, x);
	else
		GRop64To64((GArgb64*)d, (GBgra64*)s, x);
	break;
case JointCs(CsArgb64, CsRgba64):
	if (Composite)
		GComposite64To64((GArgb64*)d, (GRgba64*)s, x);
	else
		GRop64To64((GArgb64*)d, (GRgba64*)s, x);
	break;
case JointCs(CsArgb64, CsAbgr64):
	if (Composite)
		GComposite64To64((GArgb64*)d, (GAbgr64*)s, x);
	else
		GRop64To64((GArgb64*)d, (GAbgr64*)s, x);
	break;
case JointCs(CsArgb64, CsArgb64):
	if (Composite)
		GComposite64To64((GArgb64*)d, (GArgb64*)s, x);
	else
		GRop64To64((GArgb64*)d, (GArgb64*)s, x);
	break;
