// This file generated by LgiRes

#define IDD_COMPARE								6
#define IDC_TABLE								7
#define IDC_LEFT								8
#define IDC_RIGHT								9
#define IDC_COMPARE								10
#define IDC_LIST								12
#define IDC_13									13
#define IDC_14									14
#define IDC_15									15
#define IDM_FILE								500
#define IDM_SAVE_IMGS							501
#define IDM_MENU_502							502
#define IDM_EXIT								503
#define IDM_COMPARE_IMAGES						504
