
// This allows the script to fail without pulling up the debugger.
DebuggerEnabled(false);

function Func()
{
	Id = Null;
	if (!Id) // This was turning 'Id' to 'true' instead of using a register.
		return Id;

	return "Failed";
}

function ThrowAnError()
{
	Throw("Don't run me.");
}

t = Func();
Print("t=", t, "\n");

if (t)
	return false;

a = false;
if (a && ThrowAnError())
{
	return false;
}

return true;