// This file generated by LgiRes

#define IDC_COMMIT_AND_PUSH						3
#define IDC_BRANCH								11
#define IDC_BRANCH_DROPDOWN						14
#define IDC_MSG									16
#define IDC_TABLE								500
#define IDC_COMMIT								501
#define IDC_PULL								502
#define IDC_PUSH								503
#define IDC_COMMIT_TABLE						504
#define IDC_FILTER								505
#define IDC_CLEAR_FILTER						506
#define IDD_COMMIT								507
#define IDD_TOOLBAR								508
