// This file generated by LgiRes

#define IDD_TOOLBAR								1
#define IDC_TABLE								2
#define IDC_COMMIT								3
#define IDC_PULL								4
#define IDC_PUSH								5
#define IDC_FILTER								7
#define IDC_CLEAR_FILTER						8
