// This file generated by LgiRes

#define IDC_NOT_IN_LANG							505
#define IDC_IN_LANG								503
#define IDD_SEARCH								500
#define IDD_RESULTS								14
#define IDC_REF									508
#define IDC_DIFFS								24
#define IDC_TEXT								502
#define IDC_IN_CTRL								10
#define IDC_IN_DEFINES							21
#define IDD_COMPARE								23
#define IDS_16									16
#define IDS_17									17
#define IDS_19									19
#define IDC_LANG								504
#define IDS_20									20
#define IDS_25									25
#define IDS_26									26
#define IDC_IN_TEXT								501
#define IDC_DEFINE								22
#define IDC_CTRL								11
#define IDC_NOT_LANG							506
#define IDC_IN_REF								507
#define IDC_LIST								15
