#include "GMem.h"
#include "GFile.h"
#include "GProperties.h"
#include "LDateTime.h"

// From HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Time Zones

GTimeZone GTimeZones[] =
{
	{-12.00,	"Dateline (Eniwetok, Kwajalein)"},
	{-11.00,	"Samoa (Midway Island, Samoa)"},
	{-10.00,	"Hawaiian (Hawaii)"},
	{-9.00,		"Alaskan (Alaska)"},
	{-8.00,		"Pacific (Pacific Time (US & Canada); Tijuana)"},
	{-7.00,		"Mountain (Mountain Time (US & Canada))"},
	{-7.00,		"US Mountain (Arizona)"},
	{-6.00,		"Canada Central (Saskatchewan)"},
	{-6.00,		"Central America (Central America)"},
	{-6.00,		"Central (Central Time (US & Canada))"},
	{-6.00,		"Mexico (Mexico City)"},
	{-5.00,		"Eastern (Eastern Time (US & Canada))"},
	{-5.00,		"SA Pacific (Bogota, Lima, Quito)"},
	{-5.00,		"US Eastern (Indiana (East))"},
	{-4.00,		"Atlantic (Atlantic Time (Canada))"},
	{-4.00,		"Pacific SA (Santiago)"},
	{-4.00,		"SA Western (Caracas, La Paz)"},
	{-3.00,		"East South America (Brasilia)"},
	{-3.00,		"Greenland (Greenland)"},
	{-3.00,		"SA Eastern (Buenos Aires, Georgetown)"},
	{-2.50,		"Newfoundland (Newfoundland)"},
	{-2.00,		"Mid-Atlantic (Mid-Atlantic)"},
	{-1.00,		"Azores (Azores)"},
	{-1.00,		"Cape Verde (Cape Verde Is.)"},
	{0.00,		"GMT"},
	{1.00,		"Central Europe (Belgrade, Bratislava, Budapest, Ljubljana, Prague)"},
	{1.00,		"Central European (Sarajevo, Skopje, Sofija, Vilnius, Warsaw, Zagreb)"},
	{1.00,		"Romance (Brussels, Copenhagen, Madrid, Paris)"},
	{1.00,		"West Central Africa (West Central Africa)"},
	{1.00,		"West Europe (Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna)"},
	{2.00,		"East Europe (Bucharest)"},
	{2.00,		"Egypt (Cairo)"},
	{2.00,		"FLE (Helsinki, Riga, Tallin, Vilnius)"},
	{2.00,		"GTB (Athens, Istanbul, Minsk)"},
	{2.00,		"Jerusalem (Jerusalem)"},
	{2.00,		"South Africa (Harare, Pretoria)"},
	{3.00,		"Arab (Kuwait, Riyadh)"},
	{3.00,		"Arabic (Baghdad)"},
	{3.00,		"East Africa (Nairobi)"},
	{3.00,		"Russian (Moscow, St. Petersburg, Volgograd)"},
	{3.50,		"Iran (Tehran)"},
	{4.00,		"Arabian (Abu Dhabi, Muscat)"},
	{4.00,		"Caucasus (Baku, Tbilisi, Yerevan)"},
	{4.50,		"Afghanistan (Kabul)"},
	{5.00,		"Ekaterinburg (Ekaterinburg)"},
	{5.00,		"West Asia (Islamabad, Karachi, Tashkent)"},
	{5.50,		"India (Calcutta, Chennai, Mumbai, New Delhi)"},
	{5.75,		"Nepal (Kathmandu)"},
	{6.00,		"Central Asia (Astana, Dhaka)"},
	{6.00,		"N. Central Asia (Almaty, Novosibirsk)"},
	{6.00,		"Sri Lanka (Sri Jayawardenepura)"},
	{6.50,		"Myanmar (Rangoon)"},
	{7.00,		"North Asia (Krasnoyarsk)"},
	{7.00,		"SE Asia (Bangkok, Hanoi, Jakarta)"},
	{8.00,		"China (Beijing, Chongqing, Hong Kong, Urumqi)"},
	{8.00,		"North Asia East (Irkutsk, Ulaan Bataar)"},
	{8.00,		"Malay Peninsula (Kuala Lumpur, Singapore)"},
	{8.00,		"Taipei (Taipei)"},
	{8.00,		"West Australia (Perth)"},
	{9.00,		"Korea (Seoul)"},
	{9.00,		"Tokyo (Osaka, Sapporo, Tokyo)"},
	{9.00,		"Yakutsk (Yakutsk)"},
	{9.50,		"AUS Central (Darwin)"},
	{9.50,		"Cen. Australia (Adelaide)"},
	{10.00,		"AUS Eastern (Canberra, Melbourne, Sydney)"},
	{10.00,		"East Australia (Brisbane)"},
	{10.00,		"Tasmania (Hobart)"},
	{10.00,		"Vladivostok (Vladivostok)"},
	{10.00,		"West Pacific (Guam, Port Moresby)"},
	{11.00,		"Central Pacific (Magadan, Solomon Is., New Caledonia)"},
	{12.00,		"Fiji (Fiji, Kamchatka, Marshall Is.)"},
	{12.00,		"New Zealand (Auckland, Wellington)"},
	{13.00,		"Tonga (Nuku'alofa)"},
	{0,			0}
};
