/// \file
/// \brief Softbank emoji access. This file goes with the emoji glyph image
///			generated by another application. It maps the glyphs to a grid
///			where a direct relationship between character and x,y location of
///			the associated glyph is established.
#ifndef _EMOJI_H_
#define _EMOJI_H_

/// Size of the graphics cells
#define EMOJI_CELL_SIZE			20

/// The width of each group in cells
#define EMOJI_GROUP_X			16
/// The height of each group in cells
#define EMOJI_GROUP_Y			6

extern int EmojiToIconIndex(const uint32 *Str, ssize_t Len);

#endif