#ifndef _LGI_MSGS_H_
#define _LGI_MSGS_H_

enum LgiStringID
{
	// Base
	L_SUCCESS = 0,
	L_ERROR = -1,
	L_ERROR_NO_MEMORY = -2,
	L_ERROR_BAD_VALUE = -3,

	L_BTN_OK = -50,
	L_BTN_CANCEL = -51,

	// Mail lib error message ID's
	L_ERROR_ESMTP_NO_AUTHS = -100,
	L_ERROR_ESMTP_NO_FROM = -101,
	L_ERROR_UNSUPPORTED_AUTH = -102,
	L_ERROR_GENERIC = -103,

	// Text control strings
	L_TEXTCTRL_AUTO_INDENT = -200,
	L_TEXTCTRL_COPY = -201,
	L_TEXTCTRL_COPYLINK = -202,
	L_TEXTCTRL_CUT = -203,
	L_TEXTCTRL_EMAIL_TO = -204,
	L_TEXTCTRL_FIXED = -205,
	L_TEXTCTRL_GOTO_LINE = -206,
	L_TEXTCTRL_OPENURL = -207,
	L_TEXTCTRL_PASTE = -208,
	L_TEXTCTRL_REDO = -209,
	L_TEXTCTRL_UNDO = -210,
	L_TEXTCTRL_SHOW_WHITESPACE = -211,
	L_TEXTCTRL_HARD_TABS = -212,
	L_TEXTCTRL_INDENT_SIZE = -213,
	L_TEXTCTRL_TAB_SIZE = -214,
	L_TEXTCTRL_RTL = -215,

	L_TEXTCTRL_ASK_SAVE = -220,
	L_TEXTCTRL_SAVE = -221,

	// Resource sub system
	L_ERROR_RES_NO_EXE_PATH = -300,
	L_ERROR_RES_NO_LR8_FILE = -301,
	L_ERROR_RES_CREATE_OBJECT_FAILED = -302,
	L_ERROR_RES_RESOURCE_READ_FAILED = -303,

	// Font selection dialog
	L_FONTUI_BOLD = -400,
	L_FONTUI_FACE = -401,
	L_FONTUI_ITALIC = -402,
	L_FONTUI_PREVIEW = -403,
	L_FONTUI_PTSIZE = -404,
	L_FONTUI_STYLE = -405,
	L_FONTUI_TITLE = -406,
	L_FONTUI_UNDERLINE = -407,

	// Html control
	L_COPY_LINK_LOCATION = -500,
	L_VIEW_SOURCE = -501,
	L_COPY_SOURCE = -502,
	L_VIEW_IN_DEFAULT_BROWSER = -503,
	L_VIEW_IMAGES = -504,
	L_CHANGE_CHARSET = -505,

	// Colour control
	L_COLOUR_NONE = -550,

	// Find/Replay windows
	L_FR_FIND = -600,
	L_FR_FIND_WHAT = -601,
	L_FR_FIND_NEXT = -602,
	L_FR_MATCH_WORD = -603,
	L_FR_MATCH_CASE = -604,
	L_FR_REPLACE = -605,
	L_FR_REPLACE_ALL = -606,
	L_FR_REPLACE_WITH = -607,
	L_FR_SELECTION_ONLY = -608,

	// Misc
	L_TOOLBAR_SHOW_TEXT = -700,

	// Storage lib
	L_STORE_WRITE_ERR = -800,
	L_STORE_OS_ERR = -801,
	L_STORE_MISMATCH = -802,
	L_STORE_RESTART = -803,

	// Filter UI
	L_FUI_NEW_CONDITION = -900,
	L_FUI_NEW_AND = -901,
	L_FUI_NEW_OR = -902,
	L_FUI_AND = -903,
	L_FUI_OR = -904,
	L_FUI_DELETE = -905,
	L_FUI_MOVE_UP = -906,
	L_FUI_MOVE_DOWN = -907,
	L_FUI_CONFIGURE = -908,
	L_FUI_OPTIONS = -909,
	L_FUI_NOT = -910,
	L_FUI_LEGEND = -911,
	L_FUI_NEW = -912,
	L_FUI_CONDITION = -913,

	// Software update class
	L_SOFTUP_CHECKING = -1000,
	L_SOFTUP_DOWNLOADING = -1001,

	L_ERROR_UNEXPECTED_XML = -1020,
	L_ERROR_XML_PARSE = -1021,
	L_ERROR_HTTP_FAILED = -1022,
	L_ERROR_CONNECT_FAILED = -1023,
	L_ERROR_NO_URI = -1024,
	L_ERROR_URI_ERROR = -1025,
	L_ERROR_UPDATE = -1026,
	L_ERROR_COPY_FAILED = -1027,
	L_ERROR_OPENING_TEMP_FILE = -1028,

	// GDocApp
	L_DOCAPP_SAVE_CHANGE = -1100,
	L_DOCAPP_RESTART_APP = -1101,
	
	// GControlTree
	L_CONTROLTREE_NO_VALUE = -1200,
};

#endif
