// Generated by LgiRes

// This file generated by LgiRes

#define IDD_TEST								2
#define IDC_3									3
#define IDC_EDIT								5
#define IDC_COMBO								7
#define IDC_CHECKBOX							8
#define IDC_GROUP								9
#define IDC_ONE									10
#define IDC_TWO									11
#define IDC_THREE								12
#define IDC_LIST								13
#define IDC_TREE								14
#define IDC_PROGRESS							15
#define IDS_TEST_STRING							500
