// This file generated by LgiRes

#define IDC_LOAD_FILE							501
#define IDS_7									503
#define IDS_8									504
#define IDS_11									505
#define IDC_LANG								502
#define IDD_APP									506
#define IDC_CMD_LINE							500
